### ISSUE TITLE
Error with jsdom dependency.

### ISSUE THREAD

**Issue by OrdoFlammae** [learn-co-students/javascript-objects-lab-bootcamp-prep-000#3118]
I'm getting an error something like this:

1)  "before each" hook for "defines a `recipes` object":
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5).

I think it has something to do with this warning I got when the IDE tried to install the packages:

warning " > mocha-jsdom@1.2.0" has incorrect peer dependency "jsdom@>10.0.0".

I fixed this by updating the dependency `mocha-jsdom` to 2.0.0, but I think this should be fixed.

**Comment by OrdoFlammae** [comment]
This was an old error that I opened, and forgot to close when it was fixed. Sorry about that. It was an error for IDE though.

**Comment by reblim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TESTY-CLE](https://trello.com/c/u6G1eRIA/1-testy-cle)
